import "@/styles/globals.css";

import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { ReactNode } from "react";

import { Header } from "@/components/ui/header";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ClientLayout({ children }: { children: ReactNode }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${raleway.className}`}>
        <Header />
        <main className="flex flex-col items-center justify-between mt-4">{children}</main>
      </body>
    </html>
  );
}
