import "@/styles/globals.css";

import type { Metadata } from "next";
import { Archivo } from "next/font/google";

import { Header } from "@/components/header";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${archivo.className}`}>
        <Header />
        <main className="flex flex-col items-center justify-between px-24 pt-12">{children}</main>
      </body>
    </html>
  );
}
